Cite: @Gutwin2010GoneBut, @Rekimoto1997PickDrop
Cotutor: Nombre del Co-tutor Académico
Csl: input/resources/csl/acm-sig-proceedings.csl
Department: Departamento tutor académico
Language: english
Month: June
Name: Lucian Andrei Farcas
Technology: Information Systems
Title: Título
Tutor: Alfonso Niño Ramos
Year: 2024
